# Generated by Django 5.1.7 on 2025-12-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuenta",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
